services:
  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "9090:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/health/ping" ]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - DELIUS_ENABLED=false
      - NOMIS_ENABLED=false

  locations-inside-prison-db:
    image: postgres
    networks:
      - hmpps
    container_name: prison-person-data-db
    restart: unless-stopped
    ports:
      - "9432:5432"
    environment:
      - POSTGRES_PASSWORD=prison-person-data
      - POSTGRES_USER=prison-person-data
      - POSTGRES_DB=prison-person-data
      - TZ="Europe/London"

  localstack:
    image: localstack/localstack:latest
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4567:4566"
    environment:
      - SERVICES=sqs,sns,s3
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  document-service:
    image: quay.io/hmpps/hmpps-document-management-api:latest
    networks:
      - hmpps
    container_name: document-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_NAME=document-service
      - DB_SERVER=document-service-db
      - DB_USER=document-service
      - DB_PASS=document-service
      - DB_SSL_MODE=prefer
      - AWS_S3_ENDPOINT=localstack
      - HMPPS_AUTH_URL=https://sign-in-dev.hmpps.service.justice.gov.uk/auth
      - AWS_REGION=eu-west-2
    depends_on:
      localstack:
        condition: service_healthy

  document-service-db:
    image: postgres
    networks:
      - hmpps
    container_name: document-service-db
    restart: unless-stopped
    ports:
      - "9433:5432"
    environment:
      - POSTGRES_PASSWORD=document-service
      - POSTGRES_USER=document-service
      - POSTGRES_DB=document-service
      - TZ="Europe/London"

  clamav:
    image: ghcr.io/ministryofjustice/hmpps-clamav-freshclammed:latest
    networks:
      - hmpps
    container_name: clamav
    ports:
      - "3310:3310"

networks:
  hmpps:
