services:
  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "9090:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/health/ping" ]
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - DELIUS_ENABLED=false
      - NOMIS_ENABLED=false

  locations-inside-prison-db:
    image: postgres
    networks:
      - hmpps
    container_name: prison-person-data-db
    restart: unless-stopped
    ports:
      - "9432:5432"
    environment:
      - POSTGRES_PASSWORD=prison-person-data
      - POSTGRES_USER=prison-person-data
      - POSTGRES_DB=prison-person-data
      - TZ="Europe/London"

  localstack:
    image: localstack/localstack:latest
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4567:4566"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  hmpps:
