generic-service:
  nameOverride: hmpps-prison-person-api
  productId: "DPS013"

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-prison-person-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-prison-person-api-cert

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-prison-person-api:
      PRISONER_SEARCH_CLIENT_ID: "PRISONER_SEARCH_CLIENT_ID"
      PRISONER_SEARCH_CLIENT_SECRET: "PRISONER_SEARCH_CLIENT_SECRET"

    rds-postgresql-instance-output:
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      DATABASE_NAME: "database_name"
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      SPRING_FLYWAY_USER: "database_username"
      SPRING_FLYWAY_PASSWORD: "database_password"

  allowlist:
    groups:
      - internal

  modsecurity_enabled: true
  modsecurity_snippet: |
    SecRuleEngine DetectionOnly
    SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
    SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
    SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level=2"

generic-prometheus-alerts:
  targetApplication: hmpps-prison-person-api
