server:
  shutdown: immediate

api:
  base:
    url:
      oauth: http://localhost:9090/auth
      prisoner-search: http://localhost:8112

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  devtools:
    add-properties: true

  datasource:
    url: jdbc:postgresql://localhost:5432/prison-person-data?sslmode=prefer
    username: prison-person-data
    password: prison-person-data

  jpa:
    show-sql: true

