server:
  shutdown: immediate

api:
  base:
    url:
      oauth: http://localhost:9090/auth
      prisoner-search: http://localhost:8112

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  devtools:
    add-properties: true

  datasource:
    url: jdbc:postgresql://localhost:9432/prison-person-data?sslmode=prefer

  flyway:
    locations: classpath:/db/migration/common,classpath:/db/migration/dev

  jpa:
    show-sql: true

hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4567
  queues:
    prisonperson:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
      subscribeTopicId: domainevents
      subscribeFilter: >-
        {"eventType": [
          "prison-offender-events.prisoner.merged"
        ]}

  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:hmpps-domain-events-topic

database:
  superuser:
    username: prison-person-data
    password: prison-person-data
  prisonperson:
    password: prisonperson
