---
# Per environment values which override defaults in hmpps-prison-person-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prison-person-api-dev.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    EVENTS_BASE_URL: https://prison-person-api-dev.prison.service.justice.gov.uk
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISONER_SEARCH: https://prisoner-search-dev.prison.service.justice.gov.uk

  scheduledDowntime:
    enabled: true
    startup: '49 6 * * 1-5' # Start at 6.49am UTC Monday-Friday
    shutdown: '58 21 * * 1-5' # Stop at 9.58pm UTC Monday-Friday

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-prisoner-profile-non-prod
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-a40b7024a320758f: prison-person-api
