---
# Per environment values which override defaults in hmpps-prison-person-api/values.yaml

generic-service:
  ingress:
    host: prison-person-api.prison.service.justice.gov.uk

  env:
    EVENTS_PUBLISH: false
    EVENTS_SUBSCRIBE: true
    EVENTS_BASE_URL: https://prison-person-api.prison.service.justice.gov.uk
    API_OAUTH_BASE_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    API_PRISONER_SEARCH_BASE_URL: https://prisoner-search.prison.service.justice.gov.uk
    API_DOCUMENT_SERVICE_BASE_URL: https://document-api.hmpps.service.justice.gov.uk

  postgresDatabaseRestore:
    enabled: true
    env:
      SCHEMA_TO_RESTORE: "prison_person"
    namespace_secrets:
      rds-postgresql-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      rds-postgresql-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-prison-person-api-prod
  rdsAlertsDatabases:
    cloud-platform-e6f0c67759ffad65: "HMPPS Prison Person API DB (prod)"
  sqsAlertsQueueNames:
    - connect-dps-prod-prison_person_domain_events_queue
    - connect-dps-prod-prison_person_domain_events_dl