---
# Per environment values which override defaults in hmpps-prison-person-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prison-person-api-preprod.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    EVENTS_BASE_URL: https://prison-person-api-preprod.prison.service.justice.gov.uk
    API_OAUTH_BASE_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    API_PRISONER_SEARCH_BASE_URL: https://prisoner-search-preprod.prison.service.justice.gov.uk
    API_DOCUMENT_SERVICE_BASE_URL: https://document-api-preprod.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-prison-person-api-preprod
  rdsAlertsDatabases:
    cloud-platform-8dd69b293e33c4be: "HMPPS Prison Person API DB (preprod)"
  sqsAlertsQueueNames:
    - connect-dps-preprod-prison_person_domain_events_queue
    - connect-dps-preprod-prison_person_domain_events_dl