---
# Per environment values which override defaults in hmpps-prison-person-api/values.yaml

generic-service:
  ingress:
    host: prison-person-api.prison.service.justice.gov.uk

  env:
    EVENTS_BASE_URL: https://prison-person-api.prison.service.justice.gov.uk
    API_BASE_URL_OAUTH: https://sign-in.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISONER_SEARCH: https://prisoner-search.prison.service.justice.gov.uk
    API_BASE_URL_DOCUMENT_SERVICE: https://document-api.hmpps.service.justice.gov.uk

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-prisoner-profile-prod
