---
# Per environment values which override defaults in hmpps-prison-person-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: prison-person-api-dev.prison.service.justice.gov.uk

  env:
    EVENTS_PUBLISH: true
    EVENTS_SUBSCRIBE: true
    EVENTS_BASE_URL: https://prison-person-api-dev.prison.service.justice.gov.uk
    API_OAUTH_BASE_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    API_PRISONER_SEARCH_BASE_URL: https://prisoner-search-dev.prison.service.justice.gov.uk
    API_DOCUMENT_SERVICE_BASE_URL: https://document-api-dev.hmpps.service.justice.gov.uk
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

  scheduledDowntime:
    enabled: true
    startup: '30 6 * * 1-5' # Start at 6.30am UTC Monday-Friday
    shutdown: '30 21 * * 1-5' # Stop at 9.30pm UTC Monday-Friday
    retryDlqSchedule: '*/10 7-20 * * 1-5' # Every 10 minutes 7:00am - 8:50pm UTC Monday-Friday

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-prison-person-api-dev
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-a40b7024a320758f: "HMPPS Prison Person API DB (dev)"
  sqsAlertsQueueNames:
    - connect-dps-development-prison_person_domain_events_queue
    - connect-dps-development-prison_person_domain_events_dl
